apiVersion: apps/v1
kind: Deployment
metadata:
  name: temp
spec:
  replicas: 0
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: nginx
      labels:
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: adb
  namespace: kubevirt
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 5554
    protocol: TCP
    targetPort: 5555
  selector:
    kubevirt.io/vm: android
  sessionAffinity: None
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: android
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://tinyhippo.ninja:8081/android.img" # Required. Format: (http||s3)://www.myUrl.com/path/of/data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
#---
#metadata:
#  name: android
#apiVersion: kubevirt.io/v1
#kind: VirtualMachineInstance
#spec:
#  domain:
#    resources:
#      requests:
#        memory: 1024M
#    devices:
#      disks:
#      - name: mypvcdisk
#        disk: {}
#  volumes:
#    - name: mypvcdisk
#      persistentVolumeClaim:
#        claimName: android
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: android
  name: android
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: android
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: android
        resources:
          requests:
            memory: 4096Mi
      terminationGracePeriodSeconds: 0
      volumes:
      - name: android
        persistentVolumeClaim:
          claimName: android
